### JMA-USERS ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jma-users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jma-users
  template:
    metadata:
      labels:
        app: jma-users
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
        - name: jma-users
          image: crasoftinc/users:latest
          ports:
          - containerPort: 8080
          # env:
          # {{- range .Values.containerEnvVars}}
          # - name: {{ .name }}
          #   value: {{ .value | quote }}
          # {{- end}}

---
apiVersion: v1
kind: Service
metadata:
  name: jma-users
spec:
  type: ClusterIP
  selector:
    app: jma-users
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
### Gateway ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
        - name: gateway
          image: crasoftinc/gateway:latest
          ports:
          - containerPort: 8080
          # env:
          # {{- range .Values.containerEnvVars}}
          # - name: {{ .name }}
          #   value: {{ .value | quote }}
          # {{- end}}

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
### Gateway ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
        - name: gateway
          image: crasoftinc/gateway:latest
          ports:
          - containerPort: 8080
          # env:
          # {{- range .Values.containerEnvVars}}
          # - name: {{ .name }}
          #   value: {{ .value | quote }}
          # {{- end}}

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
### Gateway ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
        - name: gateway
          image: crasoftinc/gateway:latest
          ports:
          - containerPort: 8080
          # env:
          # {{- range .Values.containerEnvVars}}
          # - name: {{ .name }}
          #   value: {{ .value | quote }}
          # {{- end}}

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
### Gateway ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
        - name: gateway
          image: crasoftinc/gateway:latest
          ports:
          - containerPort: 8080
          # env:
          # {{- range .Values.containerEnvVars}}
          # - name: {{ .name }}
          #   value: {{ .value | quote }}
          # {{- end}}

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
### Gateway ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
        - name: gateway
          image: crasoftinc/gateway:latest
          ports:
          - containerPort: 8080
          # env:
          # {{- range .Values.containerEnvVars}}
          # - name: {{ .name }}
          #   value: {{ .value | quote }}
          # {{- end}}

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
### Gateway ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
        - name: gateway
          image: crasoftinc/gateway:latest
          ports:
          - containerPort: 8080
          # env:
          # {{- range .Values.containerEnvVars}}
          # - name: {{ .name }}
          #   value: {{ .value | quote }}
          # {{- end}}

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
### Gateway ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
        - name: gateway
          image: crasoftinc/gateway:latest
          ports:
          - containerPort: 8080
          # env:
          # {{- range .Values.containerEnvVars}}
          # - name: {{ .name }}
          #   value: {{ .value | quote }}
          # {{- end}}

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
### Gateway ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
        - name: gateway
          image: crasoftinc/gateway:latest
          ports:
          - containerPort: 8080
          # env:
          # {{- range .Values.containerEnvVars}}
          # - name: {{ .name }}
          #   value: {{ .value | quote }}
          # {{- end}}

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
### Gateway ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
        - name: gateway
          image: crasoftinc/gateway:latest
          ports:
          - containerPort: 8080
          # env:
          # {{- range .Values.containerEnvVars}}
          # - name: {{ .name }}
          #   value: {{ .value | quote }}
          # {{- end}}

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
