### JMA-USERS ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jma-users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jma-users
  template:
    metadata:
      labels:
        app: jma-users
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
        - name: jma-users
          image: crasoftinc/users:latest
          ports:
          - containerPort: 8080
          # env:
          # {{- range .Values.containerEnvVars}}
          # - name: {{ .name }}
          #   value: {{ .value | quote }}
          # {{- end}}

---
apiVersion: v1
kind: Service
metadata:
  name: jma-users
spec:
  type: ClusterIP
  selector:
    app: jma-users
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
### JMA-DISCOVERY ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jma-discovery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jma-discovery
  template:
    metadata:
      labels:
        app: jma-discovery
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
        - name: jma-discovery
          image: crasoftinc/discovery:latest
          ports:
          - containerPort: 8888
          # env:
          # {{- range .Values.containerEnvVars}}
          # - name: {{ .name }}
          #   value: {{ .value | quote }}
          # {{- end}}

---
apiVersion: v1
kind: Service
metadata:
  name: jma-discovery
spec:
  type: LoadBalancer
  selector:
    app: jma-discovery
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
---
### JMA-MEDIA ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jma-media
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jma-media
  template:
    metadata:
      labels:
        app: jma-media
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
        - name: jma-media
          image: crasoftinc/media:latest
          ports:
          - containerPort: 9090
          # env:
          # {{- range .Values.containerEnvVars}}
          # - name: {{ .name }}
          #   value: {{ .value | quote }}
          # {{- end}}

---
apiVersion: v1
kind: Service
metadata:
  name: jma-media
spec:
  type: ClusterIP
  selector:
    app: jma-media
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
---
### JMA-SERVICE-HISTORY ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jma-service-history
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jma-service-history
  template:
    metadata:
      labels:
        app: jma-service-history
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
        - name: jma-service-history
          image: crasoftinc/service-history:latest
          ports:
          - containerPort: 3550
          # env:
          # {{- range .Values.containerEnvVars}}
          # - name: {{ .name }}
          #   value: {{ .value | quote }}
          # {{- end}}

---
apiVersion: v1
kind: Service
metadata:
  name: jma-service-history
spec:
  type: ClusterIP
  selector:
    app: jma-service-history
  ports:
  - protocol: TCP
    port: 3550
    targetPort: 3550
---
### JMA-TRUCKS ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jma-trucks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jma-trucks
  template:
    metadata:
      labels:
        app: jma-trucks
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
        - name: jma-trucks
          image: crasoftinc/trucks:latest
          ports:
          - containerPort: 8000
          # env:
          # {{- range .Values.containerEnvVars}}
          # - name: {{ .name }}
          #   value: {{ .value | quote }}
          # {{- end}}

---
apiVersion: v1
kind: Service
metadata:
  name: jma-trucks
spec:
  type: ClusterIP
  selector:
    app: jma-trucks
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
---
### ACTION-HISTORY ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jma-action-history
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jma-action-history
  template:
    metadata:
      labels:
        app: jma-action-history
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
        - name: jma-action-history
          image: crasoftinc/action-history:latest
          ports:
          - containerPort: 7000
          # env:
          # {{- range .Values.containerEnvVars}}
          # - name: {{ .name }}
          #   value: {{ .value | quote }}
          # {{- end}}

---
apiVersion: v1
kind: Service
metadata:
  name: jma-action-history
spec:
  type: ClusterIP
  selector:
    app: jma-action-history
  ports:
  - protocol: TCP
    port: 7000
    targetPort: 7000
---
### JMA-TRAILERS ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jma-trailers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jma-trailers
  template:
    metadata:
      labels:
        app: jma-trailers
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
        - name: jma-trailers
          image: crasoftinc/trailers:latest
          ports:
          - containerPort: 9555
          # env:
          # {{- range .Values.containerEnvVars}}
          # - name: {{ .name }}
          #   value: {{ .value | quote }}
          # {{- end}}

---
apiVersion: v1
kind: Service
metadata:
  name: jma-trailers
spec:
  type: ClusterIP
  selector:
    app: jma-trailers
  ports:
  - protocol: TCP
    port: 9555
    targetPort: 9555
---
### MONGO ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
        - name: mongodb
          image: mongo
          ports:
          - containerPort: 27017
          # env:
          # {{- range .Values.containerEnvVars}}
          # - name: {{ .name }}
          #   value: {{ .value | quote }}
          # {{- end}}

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
---
### REDIS ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
        - name: redis
          image: redis
          ports:
          - containerPort: 6359
          # env:
          # {{- range .Values.containerEnvVars}}
          # - name: {{ .name }}
          #   value: {{ .value | quote }}
          # {{- end}}

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6359
    targetPort: 6359
---
### Gateway ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
        - name: gateway
          image: crasoftinc/gateway:latest
          ports:
          - containerPort: 8080
          # env:
          # {{- range .Values.containerEnvVars}}
          # - name: {{ .name }}
          #   value: {{ .value | quote }}
          # {{- end}}

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
