apiVersion: v1
kind: Secret
metadata:
  name: my-registry-key
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlkzSmhjMjltZEdsdVl6cGpjbUZ6YjJaMFh6SXdNakE9IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson